# Types of loop

In [1]:
#for loop
#Syntax 
#    for condition:
#       statement1    #inside of loop
#       statement2    #inside of loop
#    statement3        #outside of loop

In [14]:
stunames = ['Harshal','Priyanka','Khushal','Milind']
rollno = ['1','2','3','4']

In [3]:
list(range(0,6))  # range is function which is useed to give list of number

[0, 1, 2, 3, 4, 5]

In [4]:
list(range(1,6,2))

[1, 3, 5]

In [5]:
#example of for
#after collon(:) every step should be indented to put it inside the loop
for i in range(0,6):
    print(i)
print("Hi")


0
1
2
3
4
5
Hi


In [6]:
for i in range(0,6):
    print(i)
    print("Hi")


0
Hi
1
Hi
2
Hi
3
Hi
4
Hi
5
Hi


In [12]:
# i is values in the list
for i in stunames:
    print("Hi "+i)

Hi Harshal
Hi Priyanka
Hi Khushal
Hi Milind


In [15]:
#zip helps to itterate two or more list at the same time ( this is used instead of two for loop)
for i,j in zip(stunames,rollno):
    print("Hello ",i," your roll number is : ",j)

Hello  Harshal  your roll number is :  1
Hello  Priyanka  your roll number is :  2
Hello  Khushal  your roll number is :  3
Hello  Milind  your roll number is :  4


In [19]:
# problem using this concept
sales = [2343,2334,3234,2323]
profit = [435,334,234,333]

#find profit ratio for each quarter
# first create empty list
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
    
profitratio

[0.1856594110115237,
 0.143101970865467,
 0.07235621521335807,
 0.14334911752044768]

# Array

In [21]:
#linear algebra
#Scaller ex 10         (this is a dot)
#vector ex 10,20,30    (line , one direction)
#            10
#            20
#            30

#matrix    example  [10,20,30   (2 direction, x,y plane ke saman)
                    40,50,60
                    70,80,100]

#tensors this is collection of matrix   (3d)




IndentationError: unexpected indent (<ipython-input-21-1a4e94d08542>, line 9)

In [22]:
# to create array in python we need a package called numpy
# so we need to import the package
# give alieas with import ex-np


In [23]:
import numpy as np

In [24]:
# to create array from list
sales_array=np.array(sales)

In [25]:
profit_array=np.array(profit)

In [26]:
# to perform mathematical operation directly with out any loop we convert values to array
# this is done to make things faster

profit_array/sales_array

array([0.18565941, 0.14310197, 0.07235622, 0.14334912])

In [27]:
#difference between list and array
# list can have multiple type of values but array has only same data type

In [29]:
list1 = [10,5.5,'R',True]

In [31]:
type(list1[0])

int

In [32]:
type(list1[1])

float

In [33]:
type(list1[2])

str

In [34]:
type(list1[3])

bool

In [36]:
array1=np.array(list1)

In [37]:
array1

array(['10', '5.5', 'R', 'True'], dtype='<U32')

In [38]:
#U32 is unicode 32,
# basically all values are changed to string
#all values are convert into array then all values are converted to string, (string has 1st priority,float has second priority,then is integer)

In [39]:
array1[0]

'10'

In [40]:
list1 = [10,5.5,True]

In [41]:
array1=np.array(list1)

In [42]:
array1

array([10. ,  5.5,  1. ])

In [43]:
sales

[2343, 2334, 3234, 2323]

In [44]:
sales_array

array([2343, 2334, 3234, 2323])

In [45]:
#list me copy the values in list 
sales*2

[2343, 2334, 3234, 2323, 2343, 2334, 3234, 2323]

In [46]:
#in array the values are multiplied by 2
sales_array*2

array([4686, 4668, 6468, 4646])

In [47]:
sales_array

array([2343, 2334, 3234, 2323])

In [49]:
sales_array1 = sales_array[1:3]

In [50]:
sales_array1[0]

2334

In [51]:
sales_array1[0]=2222

In [52]:
sales_array1[0]

2222

In [53]:
sales_array

array([2343, 2222, 3234, 2323])

In [54]:
#child and parent both got updated
#2222 got updates in both bcz they are saved in same ram memory
#copy the array in other array o solve such issue

In [55]:
sales_array2=sales_array.copy()

In [56]:
sales_array2[2]=3000

In [57]:
type(sales_array)

numpy.ndarray

In [58]:
#ndarray stands for n dimentional array

In [61]:
sales_us = [2323,2334,2322,4353]
sales_eu = [4534,4532,4523,4643]
sales_jp = [3423,5643,3443,5656]

In [62]:
#creating a 2 d array from different 1d array

In [63]:
np.array(sales_us,sales_eu,sales_jp) #this should come inside a list,same can be done for tuple

ValueError: only 2 non-keyword arguments accepted

In [65]:
sales_matrix = np.array([sales_us,sales_eu,sales_jp])

In [66]:
sales_matrix

array([[2323, 2334, 2322, 4353],
       [4534, 4532, 4523, 4643],
       [3423, 5643, 3443, 5656]])

In [67]:
np.array([[435,566,555,444],
                 [453,345,343,343],
                 [344,454,343,564]])


array([[435, 566, 555, 444],
       [453, 345, 343, 343],
       [344, 454, 343, 564]])

In [68]:
profit_matrix=np.array([[435,566,555,444],
                 [453,345,343,343],
                 [344,454,343,564]])


In [69]:
profit_matrix

array([[435, 566, 555, 444],
       [453, 345, 343, 343],
       [344, 454, 343, 564]])

In [70]:
sales_matrix

array([[2323, 2334, 2322, 4353],
       [4534, 4532, 4523, 4643],
       [3423, 5643, 3443, 5656]])

In [71]:
profit_matrix/sales_matrix

array([[0.18725786, 0.24250214, 0.23901809, 0.10199862],
       [0.09991178, 0.07612533, 0.07583462, 0.07387465],
       [0.10049664, 0.08045366, 0.09962242, 0.09971711]])

In [72]:
sales_matrix[1][2]

4523

In [74]:
# to ,ake things simple we can do this
rdict= {'us':0,'eu':1,'jp':2}

In [75]:
qdict = {'Q1':0,'Q2':1,'Q3':2,'Q4':3}

In [76]:
sales_matrix[rdict['eu']]

array([4534, 4532, 4523, 4643])

In [78]:
sales_matrix[rdict['eu'],qdict['Q2']]

4532

In [79]:
#all value given in one list
#first 4 values are for us,next 4 for eu, and other for jp
sales_array=np.array([2343,3323,2233,3434,3443,3434,3434,5544,5645,3434,6564,6765])

In [80]:
sales_array

array([2343, 3323, 2233, 3434, 3443, 3434, 3434, 5544, 5645, 3434, 6564,
       6765])

In [83]:
np.reshape(sales_array,(3,4))

array([[2343, 3323, 2233, 3434],
       [3443, 3434, 3434, 5544],
       [5645, 3434, 6564, 6765]])

In [84]:
# the way fortron , values are populated does column by column
np.reshape(sales_array,(3,4),'F')

array([[2343, 3434, 3434, 3434],
       [3323, 3443, 5544, 6564],
       [2233, 3434, 5645, 6765]])

In [85]:
# the way c, values are populated row by row
np.reshape(sales_array,(3,4),'C')

array([[2343, 3323, 2233, 3434],
       [3443, 3434, 3434, 5544],
       [5645, 3434, 6564, 6765]])

In [86]:
#functions in numpy
#numpy is mathematical package, we can apply mathematical function


In [87]:
np.sqrt(100)

10.0

In [ ]:
np.